import { useLocationContext } from '../contexts/LocationContext';

export const useDataManager = () => {
  const {
    locations,
    loading,
    error,
    selectedLocations,
    searchQuery,
    sortBy,
    sortOrder,
    filterBy,
    addLocation,
    updateLocation,
    deleteLocation,
    deleteLocations,
    importLocations,
    exportLocations,
    exportSelectedLocations,
    selectLocation,
    selectAllLocations,
    clearSelection,
    toggleLocationSelection,
    setSearchQuery,
    setSortBy,
    setSortOrder,
    setFilterBy,
    refreshData,
    columnMapping,
    availableColumns,
    setColumnMapping,
    clearColumnMapping,
    updateAvailableColumns,
    exportCompleteBackup,
    importBackupData,
  } = useLocationContext();

  return {
    // State
    locations,
    loading,
    error,
    selectedLocations,
    searchQuery,
    sortBy,
    sortOrder,
    filterBy,
    
    // Actions
    addLocation,
    updateLocation,
    deleteLocation,
    deleteLocations,
    importLocations,
    exportLocations,
    exportSelectedLocations,
    selectLocation,
    selectAllLocations,
    clearSelection,
    toggleLocationSelection,
    setSearchQuery,
    setSortBy,
    setSortOrder,
    setFilterBy,
    refreshData,
    columnMapping,
    availableColumns,
    setColumnMapping,
    clearColumnMapping,
    updateAvailableColumns,
    exportCompleteBackup,
    importBackupData,
  };
};
